apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-configmap
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: db-for-cluster-host
spec:
  to:
    name: rds-configmap
    kind: configmap
  from:
    path: ".status.endpoint.address"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: db-for-cluster
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: db-for-cluster-port
spec:
  to:
    name: rds-configmap
    kind: configmap
  from:
    path: ".status.endpoint.port"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: db-for-cluster
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: db-for-cluster-user
spec:
  to:
    name: rds-configmap
    kind: configmap
  from:
    path: ".spec.masterUsername"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: db-for-cluster